name: Deploy

# Controls when the action will run. Triggers the workflow on push event for the master branch
on:
  push:
    branches: [ node-server ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - uses: actions/checkout@v1
      - name: Set up Node.js version
        uses: actions/setup-node@v1
        with:
          node-version: '12.x'

      - name: npm install & transpile
        run: |
          npm install
          tsc
    
      - name: 'Deploy to Azure Web App'
        uses: azure/webapps-deploy@v1
        with:
          app-name: 'mccazurewebsite'
          slot-name: 'production'
          publish-profile: ${{ secrets.webServerPublishProfile }}
          package: .
